# Generated by Django 5.2.1 on 2025-05-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_areasaber_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
    ]
