# Generated by Django 5.2.1 on 2025-06-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_areasaber_options'),
        ('app', '0002_rename_tipoavaliacao_avaliacaotipo_and_more'),
    ]

    operations = [
    ]
